
---
- name: Couchbase Installation
  hosts: all
  vars:
       username: admin
       password: Testing1234

  tasks:
  - name: Download Couchbase package
    get_url:
      url: https://packages.couchbase.com/releases/couchbase-release/couchbase-release-1.0-amd64.deb
      dest: ~/.

  - name: Install Couchbase .deb file on all machines
    shell: sudo dpkg -i ~/couchbase-release-1.0-amd64.deb

  - name: Update the packages
    shell: sudo apt-get update

  - name: Install the couchbase packages
    shell: sudo apt-get install couchbase-server-community -y

  - name: wait for 1 minute to ready the cluster
    pause:
      minutes: 1

  - name: Configure main node
    shell: /opt/couchbase/bin/couchbase-cli cluster-init -c 127.0.0.1:8091 --cluster-name CouchbaseServer --cluster-username={{ username }} --cluster-password={{ password }} --services data 
 
  - name: Create shell script to add node 
    template:
      src: /tmp/couchbase-add-node.j2 
      dest: /tmp/addnod.sh
      mode: '750'

  - name: Update the command into the script file 
    blockinfile:
              path: /tmp/addnod.sh
              insertafter: "nodetwo"
              block: |
                 /opt/couchbase/bin/couchbase-cli  server-add -c 127.0.0.1:8091 --username={{ username }} --password={{ password }} --server-add  "$nodeone" --server-add-username ={{ username }}  --server-add-password ={{ password }} --services data 
                 /opt/couchbase/bin/couchbase-cli  server-add -c 127.0.0.1:8091 --username={{ username }} --password={{ password }} --server-add  "$nodetwo" --server-add-username={{ username }}  --server-add-password={{ password }} --services data
  - name: Launch config script to add node 
    command: bash /tmp/addnod.sh


  - name: Rebalance the cluster
    shell: /opt/couchbase/bin/couchbase-cli rebalance -c 127.0.0.1:8091 -u {{ username }} -p {{ password }}
