---
- name: Couchbase Installation
  hosts: all
   
  tasks:
  - name: download Couchbase package
    get_url: 
      url: https://packages.couchbase.com/releases/couchbase-release/couchbase-release-1.0-amd64.deb 
      dest: ~/.

  - name: Install Couchbase .deb file on all machines
    shell: sudo dpkg -i ~/couchbase-release-1.0-amd64.deb

  - name: Update the packages 
    shell: sudo apt-get update 

  - name: Install the couchbase packages 
    shell: sudo apt-get install couchbase-server-community -y 
